<!DOCTYPE html>
<meta http-equiv="Expires" content="0">
<meta http-equiv="Last-Modified" content="0">
<meta http-equiv="Cache-Control" content="no-cache, mustrevalidate">
<meta http-equiv="Pragma" content="no-cache">
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Slim 3</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
    </head>
    <style type="text/css">
        table {
   border: 1px solid black;
}th, td {
    border-bottom: 1px solid #ddd;padding: 8px;
}
    </style>

    <form method="post" action="buscarlistar">
    <label>Buscar por Email: </label>
        <div><input type="text" name="txtEmail">
        <input type="submit" name="enviar">
        </div>
    </form>
    <body>
        <h2>Lista de Empleados</h2>
        <table>
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Posicion</th>
                    <th>Salario</th>
                </tr>
            </thead>
            <tbody>
                <?php if (isset($resultados)) : 
                    $data=json_decode($resultados);
                    if(is_array($data)) :
                        foreach ($data as $k => $val) : ?>
                        <tr>
                            <td><a href="ver/<?php echo $val->id?>"><?php echo $val->name; ?></a></td>
                            <td><?php echo $val->email; ?></td>
                            <td><?php echo $val->position; ?></td>
                            <td><?php echo $val->salary; ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php else : ?>
                        No hay datos
                    <?php endif; ?>
                <?php endif; ?>
            </tbody>
        </table>
      
        
    </body>
</html>
